services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./media:/media
      - ./torrents:/torrents
    ports:
      - 8989:8989
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: 'unless-stopped'
