services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - type: bind
        source: ./media
        target: /media
      - type: bind
        source: ./torrents
        target: /torrents
    ports:
      - 8989:8989
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: 'unless-stopped'
