# Jellyfin for media streaming
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    volumes:
      - ./config:/config
      - ./cache:/cache
      # Add bind volumes for Jellyfin
      - type: bind
        source: ./media
        target: /media
    # If no GPU available, comment the following
    #   lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
